[IDS-1742] feat: Branch List 출력 API
leejeongkang/Github-Api-Project pull request #1
Opened 2022-11-29 01:55 UTC by leejeongkang

2022-11-29 04:34 UTC, rhcpn reviewed
현재 코드는 특이한점은 없지만 
상위에 있는 getName 함수에 보면 컬렉션 객체를 사용한 모든 부분에 인터페이스를 사요하지 않고 전부 실제 클래스로 선언하고 반환 하도록 되어 있는데 인터페이스를 사용하는것이 나중에 코드의 컬렉션 객체 전환이나 기타 처리에 유용하기 때문에 인터페이스 사용하는걸 생활화 했으면 좋겠습니다.

ex) List<String, Object> list = new ArrayList<String, Objec>();

2022-11-30 08:28 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +        for (HashMap<String, Object> item : list) {
이것도 뭐 HashMap을 굳이 쓸필요 없에 Map을 쓰면 될것 같습니다.

2022-11-30 08:31 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
>              nameMap.put("name", item.get("name"));
해당 부분은 나중에 화면에서 리스트로 key, label 형태로 사용한다고 가정한다면 name 속성외에 key 혹은 label 에 해당하는 항목이 있으면 더 좋겠네요. key 부분은 임의로 지정해도 화면에서 key로 활용하는데 무리가 없을겁니다.

2022-11-30 08:32 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +    public Integer commitCnt(String repo) {
Cnt 같은 명칭은 DB 필드에서는 사용하는 형태지만 코드 상에서 사용하기 적합한 단어는 아닌것 같습니다.
코드 내에서는 줄임말 보다는 단어를 전부 사용하는게 좋습니다. 
불필요한 주석보다는 이름만 봐도 누구나 알수 있는 보편적인 단어를 사용해주세요 ~~

2022-11-30 08:33 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +        JsonResult result = this.restAPI.get("https://api.github.com/repos" + owner + "/" + repo + "/branches",
뭐 git 주소도 계속 반복적이니까 기왕이면 상수로 지정해서 쓰면 어떨까요
또한 주소의 경우 generate 하는 함수를 하나 만들어봐도 괜찮겠네요

2022-11-30 08:35 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +        HashMap<String, String> userMap = new HashMap<>();
요런 부분도 HashMap 으로 바로 지정하기 보다 Map 으로 ~

2022-11-30 08:36 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +        calendar.setTime(date);
요런것은 사실 코딩 스타일일 수 있는데 calendar.setTime(new Date()) 로 처리하는게 더 나을것 같습니다.
date 를 선언해서 다른 용도도 없으니까 이렇게 줄여도 괜찮을것 같습니다 ..

2022-12-01 16:27 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +    private String getURL(String repo, String key) {
음 이코드는 문제가 있습니다.
밑에 보면 계속 getURL 함수를 호출하는데, 그때마다 주소를 초기화해서 맵에 넣고 다시 리턴하는 형태라서
완전 잘못되었습니다 ...

private 함수로 getURL을 만들기 보다 클래스를 하나 만들어서 메소드를 정의하면 괜찮을것 같습니다

2022-12-01 16:29 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +            nameMap.put("id", item.get("id"));
으음 다시보니까 이미 리스트에 맵이 있는데 그걸 다시 꺼내서 옮기는거 같은데 맵의 키값 까지 같게 하려면
그대로 써도 되지 않을까요?

2022-12-01 16:30 UTC, rhcpn requested changes
새로 추가한 리뷰 부분 확인해주시고 이번엔 꼭!! 수정해주세요

2022-12-06 06:39 UTC, rhcpn commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +            keySet.addAll(item.keySet());
요 밑의 코드 세줄은 어떤 의미에요?

2022-12-06 07:20 UTC, rhcpn reviewed
이제 간단한 수정만 하고 확인 없이 바로 Merge 해주시고 ..
UI 개발을 들어가야 할것 같습니다.

UI 쪽 개발은 일단 먼저 vuex 구성 해보는걸 권장 합니다..

2022-12-06 07:55 UTC, leejeongkang commented on source/src/main/java/com/mobigen/GithubApiProject/Repo/RepoService.java
> +            keySet.addAll(item.keySet());
으음 다시보니까 이미 리스트에 맵이 있는데 그걸 다시 꺼내서 옮기는거 같은데 맵의 키값 까지 같게 하려면
그대로 써도 되지 않을까요?

위의 코멘트를 보고
기존 데이터에서 불필요한 부분을 삭제 하는 방법으로 해봤습니다.

1. HashMap의 모든 키값을 keySet 메소드를 통해서 Set<String>에 저장한다.
2. removeAll 메소드를 통해서 모든 키값에서 필요한 키값(name, id 등...)이 삭제된다.
3. 다시 item.keySet()으로 모든 키값을 가져온 후 2번 결과값들을 삭제한다. 

결과 : 차집합 2번을 통해서 내가 필요한 키값만 갖고오게된다..

2022-12-06 08:02 UTC, merged